# HTTP Server配置
[server]
	Address        = ":8199"
	ServerRoot     = "public"
	ServerAgent    = "GoJustToolc-demos"
	LogPath        = "/tmp/log/GoJustToolc-demos/server"
	NameToUriType  = 2
	RouteOverWrite = true

# 全局日志配置
[logger]
    Path   = "/tmp/log/GoJustToolc-demos"
    Level  = "all"
    Stdout = true

# 模板引擎配置
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# 数据库连接
[database]
    # link  = "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
    link  = "mysql:root:root@tcp(192.168.192.168:3306)/GoJustToolc-demos-by-lc"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "/tmp/log/GoJustToolc-demos/sql"
        Level  = "all"
        Stdout = true

# swagger api页面查看账号密码
[swagger]
    user        = "ahviplc"
    pass        = "ahviplc"
    schemes     = ["http"]
    version     = "1.0"
    title       = "示例服务API By LC"
    description = """
`GoJustToolc`基础开发框架示例服务API接口文档。
    """